openapi: 3.0.0
info:
  title: "products"
paths:
  /products:
    get:
      summary: "Get a list of product APIs in the kubernetes cluster"
      responses:
        200:
          description: "A list of product objects. Each product object specifies the hostname where it can be found."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hostname:
                      type: string